//from glfw3.h
#define TURT_KEY_SPACE              32
#define TURT_KEY_APOSTROPHE         39  
#define TURT_KEY_COMMA              44  
#define TURT_KEY_MINUS              45  
#define TURT_KEY_PERIOD             46  
#define TURT_KEY_SLASH              47  
#define TURT_KEY_0                  48
#define TURT_KEY_1                  49
#define TURT_KEY_2                  50
#define TURT_KEY_3                  51
#define TURT_KEY_4                  52
#define TURT_KEY_5                  53
#define TURT_KEY_6                  54
#define TURT_KEY_7                  55
#define TURT_KEY_8                  56
#define TURT_KEY_9                  57
#define TURT_KEY_SEMICOLON          59  
#define TURT_KEY_EQUAL              61  
#define TURT_KEY_A                  65
#define TURT_KEY_B                  66
#define TURT_KEY_C                  67
#define TURT_KEY_D                  68
#define TURT_KEY_E                  69
#define TURT_KEY_F                  70
#define TURT_KEY_G                  71
#define TURT_KEY_H                  72
#define TURT_KEY_I                  73
#define TURT_KEY_J                  74
#define TURT_KEY_K                  75
#define TURT_KEY_L                  76
#define TURT_KEY_M                  77
#define TURT_KEY_N                  78
#define TURT_KEY_O                  79
#define TURT_KEY_P                  80
#define TURT_KEY_Q                  81
#define TURT_KEY_R                  82
#define TURT_KEY_S                  83
#define TURT_KEY_T                  84
#define TURT_KEY_U                  85
#define TURT_KEY_V                  86
#define TURT_KEY_W                  87
#define TURT_KEY_X                  88
#define TURT_KEY_Y                  89
#define TURT_KEY_Z                  90
#define TURT_KEY_LEFT_BRACKET       91  
#define TURT_KEY_BACKSLASH          92  
#define TURT_KEY_RIGHT_BRACKET      93  
#define TURT_KEY_GRAVE_ACCENT       96  
#define TURT_KEY_WORLD_1            161 
#define TURT_KEY_WORLD_2            162 

/* Function keys */
#define TURT_KEY_ESCAPE             256
#define TURT_KEY_ENTER              257
#define TURT_KEY_TAB                258
#define TURT_KEY_BACKSPACE          259
#define TURT_KEY_INSERT             260
#define TURT_KEY_DELETE             261
#define TURT_KEY_RIGHT              262
#define TURT_KEY_LEFT               263
#define TURT_KEY_DOWN               264
#define TURT_KEY_UP                 265
#define TURT_KEY_PAGE_UP            266
#define TURT_KEY_PAGE_DOWN          267
#define TURT_KEY_HOME               268
#define TURT_KEY_END                269
#define TURT_KEY_CAPS_LOCK          280
#define TURT_KEY_SCROLL_LOCK        281
#define TURT_KEY_NUM_LOCK           282
#define TURT_KEY_PRINT_SCREEN       283
#define TURT_KEY_PAUSE              284
#define TURT_KEY_F1                 290
#define TURT_KEY_F2                 291
#define TURT_KEY_F3                 292
#define TURT_KEY_F4                 293
#define TURT_KEY_F5                 294
#define TURT_KEY_F6                 295
#define TURT_KEY_F7                 296
#define TURT_KEY_F8                 297
#define TURT_KEY_F9                 298
#define TURT_KEY_F10                299
#define TURT_KEY_F11                300
#define TURT_KEY_F12                301
#define TURT_KEY_F13                302
#define TURT_KEY_F14                303
#define TURT_KEY_F15                304
#define TURT_KEY_F16                305
#define TURT_KEY_F17                306
#define TURT_KEY_F18                307
#define TURT_KEY_F19                308
#define TURT_KEY_F20                309
#define TURT_KEY_F21                310
#define TURT_KEY_F22                311
#define TURT_KEY_F23                312
#define TURT_KEY_F24                313
#define TURT_KEY_F25                314
#define TURT_KEY_KP_0               320
#define TURT_KEY_KP_1               321
#define TURT_KEY_KP_2               322
#define TURT_KEY_KP_3               323
#define TURT_KEY_KP_4               324
#define TURT_KEY_KP_5               325
#define TURT_KEY_KP_6               326
#define TURT_KEY_KP_7               327
#define TURT_KEY_KP_8               328
#define TURT_KEY_KP_9               329
#define TURT_KEY_KP_DECIMAL         330
#define TURT_KEY_KP_DIVIDE          331
#define TURT_KEY_KP_MULTIPLY        332
#define TURT_KEY_KP_SUBTRACT        333
#define TURT_KEY_KP_ADD             334
#define TURT_KEY_KP_ENTER           335
#define TURT_KEY_KP_EQUAL           336
#define TURT_KEY_LEFT_SHIFT         340
#define TURT_KEY_LEFT_CONTROL       341
#define TURT_KEY_LEFT_ALT           342
#define TURT_KEY_LEFT_SUPER         343
#define TURT_KEY_RIGHT_SHIFT        344
#define TURT_KEY_RIGHT_CONTROL      345
#define TURT_KEY_RIGHT_ALT          346
#define TURT_KEY_RIGHT_SUPER        347
#define TURT_KEY_MENU               348