//from glfw3.h
#define TURT_MOUSE_BUTTON_1         0
#define TURT_MOUSE_BUTTON_2         1
#define TURT_MOUSE_BUTTON_3         2
#define TURT_MOUSE_BUTTON_4         3
#define TURT_MOUSE_BUTTON_5         4
#define TURT_MOUSE_BUTTON_6         5
#define TURT_MOUSE_BUTTON_7         6
#define TURT_MOUSE_BUTTON_8         7
#define TURT_MOUSE_BUTTON_LAST      TURT_MOUSE_BUTTON_8
#define TURT_MOUSE_BUTTON_LEFT      TURT_MOUSE_BUTTON_1
#define TURT_MOUSE_BUTTON_RIGHT     TURT_MOUSE_BUTTON_2
#define TURT_MOUSE_BUTTON_MIDDLE    TURT_MOUSE_BUTTON_3